name: FoodMap
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  get: ^4.7.2
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.5.5
  web: any
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
